const Appointment = require("../models/Appointment");
const Doctor = require("../models/Doctor");
const validDate = (value) => /^\d{4}-\d{2}-\d{2}$/.test(String(value || ""));
const populateAppointment = (query) => query.populate("patient", "name email phone").populate({ path: "doctor", populate: { path: "user", select: "name email phone" } });

const createAppointment = async (req, res) => {
  try {
    const { doctorId, appointmentDate, appointmentTime, consultationType = "Online Consultation", reason, symptoms = "", patientNotes = "" } = req.body;
    if (!doctorId || !validDate(appointmentDate) || !appointmentTime || !String(reason || "").trim()) return res.status(400).json({ success: false, message: "Date, time and reason are required" });
    const date = new Date(`${appointmentDate}T00:00:00`);
    if (Number.isNaN(date.getTime()) || appointmentDate < new Date().toISOString().slice(0, 10)) return res.status(400).json({ success: false, message: "Please choose today or a future date" });
    const doctor = await Doctor.findOne({ _id: doctorId, isApproved: true, isAvailable: true });
    if (!doctor) return res.status(404).json({ success: false, message: "Doctor is not available" });
    const weekday = date.toLocaleDateString("en-US", { weekday: "long" });
    if (doctor.availableDays.length && !doctor.availableDays.includes(weekday)) return res.status(400).json({ success: false, message: `Doctor is not available on ${weekday}` });
    const exists = await Appointment.findOne({ doctor: doctorId, appointmentDate, appointmentTime, status: { $in: ["pending", "confirmed"] } });
    if (exists) return res.status(409).json({ success: false, message: "This time slot is already booked" });
    const appointment = await Appointment.create({ patient: req.user._id, doctor: doctorId, appointmentDate, appointmentTime, consultationType, reason: String(reason).trim(), symptoms: String(symptoms).trim(), patientNotes: String(patientNotes).trim() });
    res.status(201).json({ success: true, message: "Appointment booked successfully", appointment: await populateAppointment(Appointment.findById(appointment._id)) });
  } catch (error) { console.error("CREATE APPOINTMENT ERROR:", error); res.status(500).json({ success: false, message: "Failed to create appointment" }); }
};
const getPatientAppointments = async (req, res) => { try { res.json({ success: true, appointments: await populateAppointment(Appointment.find({ patient: req.user._id }).sort({ appointmentDate: 1, appointmentTime: 1 })) }); } catch (e) { res.status(500).json({ success: false, message: "Failed to load appointments" }); } };
const getDoctorAppointments = async (req, res) => { try { const doctor = await Doctor.findOne({ user: req.user._id }); if (!doctor) return res.status(404).json({ success: false, message: "Doctor profile not found" }); res.json({ success: true, appointments: await populateAppointment(Appointment.find({ doctor: doctor._id }).sort({ appointmentDate: 1, appointmentTime: 1 })) }); } catch (e) { res.status(500).json({ success: false, message: "Failed to load appointments" }); } };
const getAppointmentById = async (req, res) => { try { const appointment = await populateAppointment(Appointment.findById(req.params.id)); if (!appointment) return res.status(404).json({ success: false, message: "Appointment not found" }); const doctor = await Doctor.findById(appointment.doctor._id); const allowed = appointment.patient._id.toString() === req.user._id.toString() || doctor?.user.toString() === req.user._id.toString() || req.user.role === "admin"; if (!allowed) return res.status(403).json({ success: false, message: "Access denied" }); res.json({ success: true, appointment }); } catch (e) { res.status(400).json({ success: false, message: "Invalid appointment id" }); } };
const updateAppointmentStatus = async (req, res) => { try { const { status, doctorNotes } = req.body; if (!["confirmed", "rejected", "completed"].includes(status)) return res.status(400).json({ success: false, message: "Invalid appointment status" }); const doctor = await Doctor.findOne({ user: req.user._id }); if (!doctor) return res.status(403).json({ success: false, message: "Doctor profile not found" }); const appointment = await Appointment.findOneAndUpdate({ _id: req.params.id, doctor: doctor._id }, { status, ...(doctorNotes !== undefined ? { doctorNotes } : {}) }, { new: true, runValidators: true }); if (!appointment) return res.status(404).json({ success: false, message: "Appointment not found" }); res.json({ success: true, message: "Appointment status updated", appointment }); } catch (e) { res.status(500).json({ success: false, message: "Failed to update appointment" }); } };
const cancelAppointment = async (req, res) => { try { const appointment = await Appointment.findOne({ _id: req.params.id, patient: req.user._id }); if (!appointment) return res.status(404).json({ success: false, message: "Appointment not found" }); if (["completed", "cancelled"].includes(appointment.status)) return res.status(400).json({ success: false, message: "Appointment cannot be cancelled" }); appointment.status = "cancelled"; appointment.cancellationReason = String(req.body.cancellationReason || "").trim(); await appointment.save(); res.json({ success: true, message: "Appointment cancelled successfully", appointment }); } catch (e) { res.status(500).json({ success: false, message: "Failed to cancel appointment" }); } };
const getBookedSlots = async (req, res) => { try { const { doctorId, date } = req.query; if (!doctorId || !validDate(date)) return res.status(400).json({ success: false, message: "Doctor and valid date are required" }); const appointments = await Appointment.find({ doctor: doctorId, appointmentDate: date, status: { $in: ["pending", "confirmed"] } }).select("appointmentTime"); res.json({ success: true, bookedSlots: appointments.map((item) => item.appointmentTime) }); } catch (e) { res.status(500).json({ success: false, message: "Failed to load booked slots" }); } };
module.exports = { createAppointment, getPatientAppointments, getDoctorAppointments, getAppointmentById, updateAppointmentStatus, cancelAppointment, getBookedSlots };
